name: dio_either
description: is a Dart package designed to simplify HTTP request handling by integrating the capabilities of Dio, dio_smart_retry, and Logger
version: 1.1.14
repository: https://github.com/anjarnaufals/dio_either
environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  dio: ^5.7.0
  dio_smart_retry: ^6.0.0
  either_dart: ^1.0.0
  http_mock_adapter: ^0.6.1
  logger: ^2.4.0

dev_dependencies:
  collection: ^1.18.0
  lints: ^3.0.0
  test: ^1.24.0
