name: dio_either
description: is a Dart package designed to simplify HTTP request handling by integrating the capabilities of Dio, dio_smart_retry, and Logger
version: 1.1.15
repository: https://github.com/anjarnaufals/dio_either
environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  dio: ^5.8.0+1
  dio_smart_retry: ^7.0.1
  either_dart: ^1.0.0
  http_mock_adapter: ^0.6.1
  logger: ^2.4.0

dev_dependencies:
  collection: ^1.19.0
  lints: ^5.1.1
  test: ^1.24.0
